### ISSUE TITLE
Question: Why not available at npm?

### ISSUE THREAD

**Issue by tlindener** [tbasse/fritzbox-callmonitor#1]
Hi,

why is this not available via vpm?

**Comment by webworka** [comment]
Because I do not longer maintain this and also do not need it for myself anymore ;-)

**Comment by tbasse** [comment]
@tlindener, good question. Just published it to npm as [node-fritzbox-callmonitor](https://www.npmjs.com/package/node-fritzbox-callmonitor).

**Comment by tbasse** [comment]
@webworka, I'd appreciate if you don't pass yourself off as a maintainer. Thanks.
