### ISSUE TITLE
JS eval fails

### ISSUE THREAD

**Issue by tlindener** [tbasse/fritzbox-callmonitor#2]
Hi,

thanks for adding the module to npm! 

I found another issue while playing around with the library. 

When I try to parse the data emitted by the events I get SyntaxError: Unexpected token t errors. 

Is it possible for you to emit only valid json objects? It would be really great!

And of course thanks for your initial work! :+1:

**Comment by tbasse** [comment]
Hi,

can you explain a bit more how what you are doing with the responses ("When I try to parse the data")?
And would it be possible to post the unparsed response where your parsing fails? That would help me a lot figuring out what happens because I don't have a fritzbox around right now.
